Sem 5/Dotnet/AdminPanelCrud/Models/Bill.cs
using System.ComponentModel.DataAnnotations;

namespace AdminPanelCrud.Models
{
    public class Bill
    {
        [Required]
        public int BillID { get; set; }
        [Required]
        public string BillNumber { get; set; }
        [Required]
        public DateTime BillDate { get; set; }
        [Required]
        public int OrderID { get; set; }
        [Required]
        public decimal TotalAmount { get; set; }
        [Required]
        public decimal Discount { get; set; }
        [Required]
        public decimal NetAmount { get; set; }
        [Required]
        public int UserID { get; set; }
    }
}

Sem 5/Dotnet/AdminPanelCrud/Controllers/BillController.cs
using AdminPanelCrud.Models;
using Microsoft.AspNetCore.Mvc;

namespace AdminPanelCrud.Controllers
{
    public class BillController : Controller
    {
        List<Bill> bills = new List<Bill> { 
            new Bill{ 
                UserID = 1,
                TotalAmount = 0,
                BillDate = DateTime.Now,
                BillID = 1,
                BillNumber = "dbvhd",
                Discount = 0,
                NetAmount = 0,
                OrderID = 0
            },
            new Bill{
                UserID = 1,
                TotalAmount = 0,
                BillDate = DateTime.Now,
                BillID = 1,
                BillNumber = "dbvhd",
                Discount = 0,
                NetAmount = 0,
                OrderID = 0
            },
            new Bill{
                UserID = 1,
                TotalAmount = 0,
                BillDate = DateTime.Now,
                BillID = 1,
                BillNumber = "dbvhd",
                Discount = 0,
                NetAmount = 0,
                OrderID = 0
            },
            new Bill{
                UserID = 1,
                TotalAmount = 0,
                BillDate = DateTime.Now,
                BillID = 1,
                BillNumber = "dbvhd",
                Discount = 0,
                NetAmount = 0,
                OrderID = 0
            },
            new Bill{
                UserID = 1,
                TotalAmount = 0,
                BillDate = DateTime.Now,
                BillID = 1,
                BillNumber = "dbvhd",
                Discount = 0,
                NetAmount = 0,
                OrderID = 0
            },
        };
        public IActionResult Index()
        {
            return View(bills);
        }

        public IActionResult BillAddEdit()
        {
            return View();
        }
    }
}

Sem 5/Dotnet/AdminPanelCrud/Views/Bill/BillAddEdit.cshtml
@model Bill
<div class="card-body">
    <h5 class="card-title">Bill List Form</h5>

    <!-- Vertical Form -->
    <form class="row g-3">
        <input type="hidden" name="BillID" />
        <div class="col-12">
            <label for="inputNanme4" class="form-label">BillNumber</label>
            <input type="text" class="form-control" asp-for="BillNumber">
            <span asp-validation-for="BillNumber"></span>
        </div>
        <div class="col-12">
            <label for="inputEmail4" class="form-label">BillDate</label>
            <input type="date" asp-for="BillDate" id="inputEmail4">
            <span asp-validation-for="BillDate"></span>
        </div>
        <div class="col-12">
            <label for="inputPassword4" class="form-label">OrderID</label>
            <input type="number" asp-for="OrderID" class="form-control" id="inputPassword4">
            <span asp-validation-for="OrderID"></span>
        </div>
        <div class="col-12">
            <label for="inputAddress" class="form-label">TotalAmount</label>
            <input type="number" asp-for="TotalAmount" class="form-control" id="inputAddress">
            <span asp-validation-for="TotalAmount"></span>
        </div>
        <div class="col-12">
            <label for="inputAddress" class="form-label">Discount</label>
            <input type="number" asp-for="Discount" class="form-control" id="inputAddress">
            <span asp-validation-for="Discount"></span>
        </div>
        <div class="col-12">
            <label for="inputAddress" class="form-label">NetAmount</label>
            <input type="number" asp-for="NetAmount" class="form-control" id="inputAddress">
            <span asp-validation-for="NetAmount"></span>
        </div>
        <div class="col-12">
            <label for="inputAddress" class="form-label">UserID</label>
            <input type="number" class="form-control" asp-for="UserID" id="inputAddress">
            <span asp-validation-for="UserID" class="text-danger"></span>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a asp-action="Index" asp-controller="Bill" class="btn btn-secondary">Cancel</a>
        </div>
    </form><!-- Vertical Form -->

</div>

@section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Sem 5/Dotnet/AdminPanelCrud/Views/Bill/Index.cshtml
@model List<Bill>

<div class="card-body">
    <h5 class="card-title">Datatables</h5>
    <p>Add lightweight datatables to your project with using the <a href="https://github.com/fiduswriter/Simple-DataTables" target="_blank">Simple DataTables</a> library. Just add <code>.datatable</code> class name to any table you wish to conver to a datatable. Check for <a href="https://fiduswriter.github.io/simple-datatables/demos/" target="_blank">more examples</a>.</p>

    <!-- Table with stripped rows -->
    <div class="datatable-wrapper datatable-loading no-footer sortable searchable fixed-columns">
        <div class="datatable-top">
            <div class="datatable-dropdown">
                <label>
                    <select class="datatable-selector" name="per-page"><option value="5">5</option><option value="10" selected="">10</option><option value="15">15</option><option value="-1">All</option></select> entries per page
                </label>
            </div>
            <div class="datatable-search">
                <input class="datatable-input" placeholder="Search..." type="search" name="search" title="Search within table">
            </div>
            <div>
                <a asp-controller="Bill" asp-action="BillAddEdit" class="btn btn-success">ADD</a>
            </div>
        </div>
        <div class="datatable-container">
            <table class="table datatable datatable-table">

                <thead>
                <th>BillID</th>
                <th>BillNumber</th>
                <th>BillDate</th>
                <th>OrderID</th>
                <th>TotalAmount</th>
                <th>Discount</th>
                <th>NetAmount</th>
                <th>User ID</th>
                <th colspan="2"> Actions</th>
                </thead>
                <tbody>
                    @foreach (var temp in Model)
                    {
                        <tr>
                            <td>@temp.BillID</td>
                            <td>@temp.BillNumber</td>
                            <td>@temp.BillDate</td>
                            <td>@temp.OrderID</td>
                            <td>@temp.TotalAmount</td>
                            <td>@temp.Discount</td>
                            <td>@temp.NetAmount</td>
                            <td>@temp.UserID</td>
                            <td><a class="btn btn-primary">EDIT</a></td>
                            <td><a class="btn btn-danger">DELETE</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="datatable-bottom">
            <div class="datatable-info">Showing 1 to 10 of 100 entries</div>
            <nav class="datatable-pagination"><ul class="datatable-pagination-list"><li class="datatable-pagination-list-item datatable-hidden datatable-disabled"><button data-page="1" class="datatable-pagination-list-item-link" aria-label="Page 1">‹</button></li><li class="datatable-pagination-list-item datatable-active"><button data-page="1" class="datatable-pagination-list-item-link" aria-label="Page 1">1</button></li><li class="datatable-pagination-list-item"><button data-page="2" class="datatable-pagination-list-item-link" aria-label="Page 2">2</button></li><li class="datatable-pagination-list-item"><button data-page="3" class="datatable-pagination-list-item-link" aria-label="Page 3">3</button></li><li class="datatable-pagination-list-item"><button data-page="4" class="datatable-pagination-list-item-link" aria-label="Page 4">4</button></li><li class="datatable-pagination-list-item"><button data-page="5" class="datatable-pagination-list-item-link" aria-label="Page 5">5</button></li><li class="datatable-pagination-list-item"><button data-page="6" class="datatable-pagination-list-item-link" aria-label="Page 6">6</button></li><li class="datatable-pagination-list-item"><button data-page="7" class="datatable-pagination-list-item-link" aria-label="Page 7">7</button></li><li class="datatable-pagination-list-item datatable-ellipsis datatable-disabled"><button class="datatable-pagination-list-item-link">…</button></li><li class="datatable-pagination-list-item"><button data-page="10" class="datatable-pagination-list-item-link" aria-label="Page 10">10</button></li><li class="datatable-pagination-list-item"><button data-page="2" class="datatable-pagination-list-item-link" aria-label="Page 2">›</button></li></ul></nav>
        </div>
    </div>
    <!-- End Table with stripped rows -->

</div>