Sem 5/Dotnet/AdminPanelCrud/Models/OrderDetail.cs
using System.ComponentModel.DataAnnotations;

namespace AdminPanelCrud.Models
{
    public class OrderDetail
    {
        [Required]
        public int OrderDetailID { get; set; }
        [Required]
        public int OrderID { get; set; }
        [Required]
        public int ProductID { get; set; }
        [Required]
        public int Quantity { get; set; }
        [Required]
        public decimal Amount { get; set; }
        [Required]
        public decimal TotalAmount { get; set; }
        [Required]
        public int UserID { get; set; }
    }
}

Sem 5/Dotnet/AdminPanelCrud/Controllers/OrderDetailController.cs
using AdminPanelCrud.Models;
using Microsoft.AspNetCore.Mvc;

namespace AdminPanelCrud.Controllers
{
    public class OrderDetailController : Controller
    {
        List<OrderDetail> orderdetail = new List<OrderDetail> { 
            new OrderDetail{ 
                OrderDetailID = 1,
                Amount = 1,
                OrderID = 2,
                ProductID = 3,
                Quantity = 4,
                TotalAmount = 5,
                UserID = 6,
            },
            new OrderDetail{
                OrderDetailID = 1,
                Amount = 1,
                OrderID = 2,
                ProductID = 3,
                Quantity = 4,
                TotalAmount = 5,
                UserID = 6,
            },
            new OrderDetail{
                OrderDetailID = 1,
                Amount = 1,
                OrderID = 2,
                ProductID = 3,
                Quantity = 4,
                TotalAmount = 5,
                UserID = 6,
            },
            new OrderDetail{
                OrderDetailID = 1,
                Amount = 1,
                OrderID = 2,
                ProductID = 3,
                Quantity = 4,
                TotalAmount = 5,
                UserID = 6,
            },
            new OrderDetail{
                OrderDetailID = 1,
                Amount = 1,
                OrderID = 2,
                ProductID = 3,
                Quantity = 4,
                TotalAmount = 5,
                UserID = 6,
            }
        };
        public IActionResult Index()
        {
            return View(orderdetail);
        }

        public IActionResult OrderDetailAddEdit()
        {
            return View();
        }
    }
}

Sem 5/Dotnet/AdminPanelCrud/Views/OrderDetail/Index.cshtml
@model List<OrderDetail>

<div class="card-body">
    <h5 class="card-title">Datatables</h5>
    <p>Add lightweight datatables to your project with using the <a href="https://github.com/fiduswriter/Simple-DataTables" target="_blank">Simple DataTables</a> library. Just add <code>.datatable</code> class name to any table you wish to conver to a datatable. Check for <a href="https://fiduswriter.github.io/simple-datatables/demos/" target="_blank">more examples</a>.</p>

    <!-- Table with stripped rows -->
    <div class="datatable-wrapper datatable-loading no-footer sortable searchable fixed-columns">
        <div class="datatable-top">
            <div class="datatable-dropdown">
                <label>
                    <select class="datatable-selector" name="per-page"><option value="5">5</option><option value="10" selected="">10</option><option value="15">15</option><option value="-1">All</option></select> entries per page
                </label>
            </div>
            <div class="datatable-search">
                <input class="datatable-input" placeholder="Search..." type="search" name="search" title="Search within table">
            </div>
            <div>
                <a asp-controller="OrderDetail" asp-action="OrderDetailAddEdit" class="btn btn-success">ADD</a>
            </div>
        </div>
        <div class="datatable-container">
            <table class="table datatable datatable-table">

                <thead>
                <th>Order Detail ID</th>
                <th>Order ID</th>
                <th>Product ID</th>
                <th>Quantity</th>
                <th>Amount</th>
                <th>Total Amount</th>
                <th>User ID</th>
                <th colspan="2"> Actions</th>
                </thead>
                <tbody>
                    @foreach (var temp in Model)
                    {
                        <tr>
                            <td>@temp.OrderDetailID</td>
                            <td>@temp.OrderID</td>
                            <td>@temp.ProductID</td>
                            <td>@temp.Quantity</td>
                            <td>@temp.Amount</td>
                            <td>@temp.TotalAmount</td>
                            <td>@temp.UserID</td>
                            <td><a class="btn btn-primary">EDIT</a></td>
                            <td><a class="btn btn-danger">DELETE</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="datatable-bottom">
            <div class="datatable-info">Showing 1 to 10 of 100 entries</div>
            <nav class="datatable-pagination"><ul class="datatable-pagination-list"><li class="datatable-pagination-list-item datatable-hidden datatable-disabled"><button data-page="1" class="datatable-pagination-list-item-link" aria-label="Page 1">‹</button></li><li class="datatable-pagination-list-item datatable-active"><button data-page="1" class="datatable-pagination-list-item-link" aria-label="Page 1">1</button></li><li class="datatable-pagination-list-item"><button data-page="2" class="datatable-pagination-list-item-link" aria-label="Page 2">2</button></li><li class="datatable-pagination-list-item"><button data-page="3" class="datatable-pagination-list-item-link" aria-label="Page 3">3</button></li><li class="datatable-pagination-list-item"><button data-page="4" class="datatable-pagination-list-item-link" aria-label="Page 4">4</button></li><li class="datatable-pagination-list-item"><button data-page="5" class="datatable-pagination-list-item-link" aria-label="Page 5">5</button></li><li class="datatable-pagination-list-item"><button data-page="6" class="datatable-pagination-list-item-link" aria-label="Page 6">6</button></li><li class="datatable-pagination-list-item"><button data-page="7" class="datatable-pagination-list-item-link" aria-label="Page 7">7</button></li><li class="datatable-pagination-list-item datatable-ellipsis datatable-disabled"><button class="datatable-pagination-list-item-link">…</button></li><li class="datatable-pagination-list-item"><button data-page="10" class="datatable-pagination-list-item-link" aria-label="Page 10">10</button></li><li class="datatable-pagination-list-item"><button data-page="2" class="datatable-pagination-list-item-link" aria-label="Page 2">›</button></li></ul></nav>
        </div>
    </div>
    <!-- End Table with stripped rows -->

</div>

Sem 5/Dotnet/AdminPanelCrud/Views/OrderDetail/OrderDetailAddEdit.cshtml
@model OrderDetail
<div class="card-body">
    <h5 class="card-title">Order Detail List Form</h5>

    <!-- Vertical Form -->
    <form class="row g-3">
        <input type="hidden" name="OrderDetailID" />
        <div class="col-12">
            <label for="inputNanme4" class="form-label">Order ID</label>
            <input type="text" class="form-control" asp-for="OrderID">
            <span asp-validation-for="OrderID"></span>
        </div>
        <div class="col-12">
            <label for="inputEmail4" class="form-label">Product ID</label>
            <input type="number" asp-for="ProductID" class="form-control" id="inputEmail4">
            <span asp-validation-for="ProductID"></span>
        </div>
        <div class="col-12">
            <label for="inputPassword4" class="form-label">Quantity</label>
            <input type="text" asp-for="Quantity" class="form-control" id="inputPassword4">
            <span asp-validation-for="Quantity"></span>
        </div>
        <div class="col-12">
            <label for="inputAddress" class="form-label">Amount</label>
            <input type="number" asp-for="Amount" class="form-control" id="inputAddress">
            <span asp-validation-for="Amount"></span>
        </div>
        <div class="col-12">
            <label for="inputAddress" class="form-label">TotalAmount</label>
            <input type="text" asp-for="TotalAmount" class="form-control" id="inputAddress">
            <span asp-validation-for="TotalAmount"></span>
        </div>
        <div class="col-12">
            <label for="inputAddress" class="form-label">UserID</label>
            <input type="number" class="form-control" asp-for="UserID" id="inputAddress">
            <span asp-validation-for="UserID" class="text-danger"></span>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a asp-action="Index" asp-controller="OrderDetail" class="btn btn-secondary">Cancel</a>
        </div>
    </form><!-- Vertical Form -->

</div>

@section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}